name: CI CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: "upload dag directory as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: dag-directory
          path: dags

      - name: "upload dag artifact to google cloud storage"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "dags"
          destination: "cf-cloud-composer-dags"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: "set up google cloud sdk"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "install kubectl"
        run: "gcloud components install kubectl"

      - name: "delete cloud composer dag from airflow"
        continue-on-error: true
        run: "gcloud composer environments run etl-orchestration-pool \
          --location us-central1 \
          dags delete -- snowflake-bq"

      - name: "deploy cloud composer dag"
        run: "gcloud composer environments storage dags import \
          --environment etl-orchestration-pool \
          --location us-central1 \
          --source gs://cf-cloud-composer-dags/dags/snowflake-bq.py"
